name: CI Python

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10']

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cachear dependencias
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Instalar dependencias y flake8
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt flake8 pytest

      - name: Revisar código con flake8
        run: python3 -m flake8 app/
        continue-on-error: false

      - name: Ejecutar pruebas
        run: python3 -m pytest
